[2021-12-19 20:14:33,688] logger_util.py->logs line:73 [INFO] ----------接口测试开始----------
[2021-12-19 20:14:33,691] logger_util.py->logs line:73 [INFO] 接口名称：成功获取token鉴权码
[2021-12-19 20:14:33,692] logger_util.py->logs line:73 [INFO] 请求方式：get
[2021-12-19 20:14:33,692] logger_util.py->logs line:73 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2021-12-19 20:14:33,692] logger_util.py->logs line:73 [INFO] 请求params参数：{'appid': 'wx8a9de038e93f77ab', 'secret': '8326fc915928dee3165720c910effb86', 'grant_type': 'client_credential'}
[2021-12-19 20:14:34,070] logger_util.py->logs line:73 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 'access_token'}]
[2021-12-19 20:14:34,070] logger_util.py->logs line:73 [INFO] 实际结果：{'access_token': '52_aJyuD9I2_ijEcXrL-scAJsYrVJvtGVxRFsHqDNlzLPJwDFlO_-q49fuy720ZEMRVlfEIQezMtXcbLJh743_pWc7RqHofpWqKX1pg5tlHga_YfS-PcNJ6ULdrIiYTnIX0x_grwsnSdl077xXFLCFbAGAZQT', 'expires_in': 7200}
[2021-12-19 20:14:34,070] logger_util.py->logs line:73 [INFO] 接口测试成功
[2021-12-19 20:14:34,071] logger_util.py->logs line:73 [INFO] ----------接口测试结束----------

[2021-12-19 20:14:34,075] logger_util.py->logs line:73 [INFO] ----------接口测试开始----------
[2021-12-19 20:14:34,077] logger_util.py->logs line:73 [INFO] 接口名称：检查appid为空
[2021-12-19 20:14:34,077] logger_util.py->logs line:73 [INFO] 请求方式：get
[2021-12-19 20:14:34,078] logger_util.py->logs line:73 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2021-12-19 20:14:34,078] logger_util.py->logs line:73 [INFO] 请求params参数：{'appid': '', 'secret': '8326fc915928dee3165720c910effb86', 'grant_type': 'client_credential'}
[2021-12-19 20:14:34,128] logger_util.py->logs line:73 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 41002}]
[2021-12-19 20:14:34,128] logger_util.py->logs line:73 [INFO] 实际结果：{'errcode': 41002, 'errmsg': 'appid missing rid: 61bf222a-32957cd5-31569440'}
[2021-12-19 20:14:34,128] logger_util.py->logs line:73 [INFO] 接口测试成功
[2021-12-19 20:14:34,128] logger_util.py->logs line:73 [INFO] ----------接口测试结束----------

[2021-12-19 20:14:34,136] logger_util.py->logs line:73 [INFO] ----------接口测试开始----------
[2021-12-19 20:14:34,139] logger_util.py->logs line:73 [INFO] 接口名称：检查secret为空
[2021-12-19 20:14:34,139] logger_util.py->logs line:73 [INFO] 请求方式：get
[2021-12-19 20:14:34,139] logger_util.py->logs line:73 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2021-12-19 20:14:34,139] logger_util.py->logs line:73 [INFO] 请求params参数：{'appid': 'wx8a9de038e93f77ab', 'secret': '', 'grant_type': 'client_credential'}
[2021-12-19 20:14:34,261] logger_util.py->logs line:73 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 41004}]
[2021-12-19 20:14:34,262] logger_util.py->logs line:73 [INFO] 实际结果：{'errcode': 41004, 'errmsg': 'appsecret missing rid: 61bf222a-474fb4a5-4895ae6d'}
[2021-12-19 20:14:34,262] logger_util.py->logs line:73 [INFO] 接口测试成功
[2021-12-19 20:14:34,262] logger_util.py->logs line:73 [INFO] ----------接口测试结束----------

[2021-12-19 20:14:34,268] logger_util.py->logs line:73 [INFO] ----------接口测试开始----------
[2021-12-19 20:14:34,272] logger_util.py->logs line:73 [INFO] 接口名称：创建标签接口
[2021-12-19 20:14:34,272] logger_util.py->logs line:73 [INFO] 请求方式：post
[2021-12-19 20:14:34,272] logger_util.py->logs line:73 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/tags/create?access_token=52_aJyuD9I2_ijEcXrL-scAJsYrVJvtGVxRFsHqDNlzLPJwDFlO_-q49fuy720ZEMRVlfEIQezMtXcbLJh743_pWc7RqHofpWqKX1pg5tlHga_YfS-PcNJ6ULdrIiYTnIX0x_grwsnSdl077xXFLCFbAGAZQT
[2021-12-19 20:14:34,272] logger_util.py->logs line:73 [INFO] 请求json参数：{'tag': {'name': '码尚教育85866'}}
[2021-12-19 20:14:34,535] logger_util.py->logs line:73 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2021-12-19 20:14:34,536] logger_util.py->logs line:73 [INFO] 实际结果：{'tag': {'id': 245, 'name': '码尚教育85866'}}
[2021-12-19 20:14:34,536] logger_util.py->logs line:73 [INFO] 接口测试成功
[2021-12-19 20:14:34,536] logger_util.py->logs line:73 [INFO] ----------接口测试结束----------

[2021-12-19 20:14:34,544] logger_util.py->logs line:73 [INFO] ----------接口测试开始----------
[2021-12-19 20:14:34,547] logger_util.py->logs line:73 [INFO] 接口名称：删除系统标签
[2021-12-19 20:14:34,547] logger_util.py->logs line:73 [INFO] 请求方式：post
[2021-12-19 20:14:34,548] logger_util.py->logs line:73 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/tags/delete?access_token=52_aJyuD9I2_ijEcXrL-scAJsYrVJvtGVxRFsHqDNlzLPJwDFlO_-q49fuy720ZEMRVlfEIQezMtXcbLJh743_pWc7RqHofpWqKX1pg5tlHga_YfS-PcNJ6ULdrIiYTnIX0x_grwsnSdl077xXFLCFbAGAZQT
[2021-12-19 20:14:34,548] logger_util.py->logs line:73 [INFO] 请求json参数：{'tag': {'id': 1}}
[2021-12-19 20:14:34,777] logger_util.py->logs line:73 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2021-12-19 20:14:34,777] logger_util.py->logs line:73 [INFO] 实际结果：{'errcode': 45058, 'errmsg': "can't modify sys tag hint: [GJjFfIpre-kaj2EA] rid: 61bf222a-0be168c0-1e153838"}
[2021-12-19 20:14:34,778] logger_util.py->logs line:73 [INFO] 接口测试成功
[2021-12-19 20:14:34,778] logger_util.py->logs line:73 [INFO] ----------接口测试结束----------

[2021-12-19 20:14:34,787] logger_util.py->logs line:73 [INFO] ----------接口测试开始----------
[2021-12-19 20:14:34,791] logger_util.py->logs line:73 [INFO] 接口名称：查询标签接口
[2021-12-19 20:14:34,792] logger_util.py->logs line:73 [INFO] 请求方式：get
[2021-12-19 20:14:34,792] logger_util.py->logs line:73 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/tags/get?access_token=52_aJyuD9I2_ijEcXrL-scAJsYrVJvtGVxRFsHqDNlzLPJwDFlO_-q49fuy720ZEMRVlfEIQezMtXcbLJh743_pWc7RqHofpWqKX1pg5tlHga_YfS-PcNJ6ULdrIiYTnIX0x_grwsnSdl077xXFLCFbAGAZQT
[2021-12-19 20:14:35,002] logger_util.py->logs line:73 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 'tags'}]
[2021-12-19 20:14:35,002] logger_util.py->logs line:73 [INFO] 实际结果：{'tags': [{'id': 2, 'name': '星标组', 'count': 0}, {'id': 103, 'name': '码尚教育20312', 'count': 0}, {'id': 113, 'name': '码尚教育97938', 'count': 0}, {'id': 114, 'name': '码尚教育30279', 'count': 0}, {'id': 151, 'name': '码尚教育99551', 'count': 0}, {'id': 200, 'name': '码尚教育32207', 'count': 0}, {'id': 201, 'name': '百里老师1639663216', 'count': 0}, {'id': 202, 'name': '码尚教育15402', 'count': 0}, {'id': 203, 'name': '码尚教育92615', 'count': 0}, {'id': 204, 'name': '码尚教育74782', 'count': 0}, {'id': 205, 'name': '码尚教育81929', 'count': 0}, {'id': 206, 'name': '码尚教育86451', 'count': 0}, {'id': 207, 'name': '码尚教育48589', 'count': 0}, {'id': 228, 'name': '码尚教育74232', 'count': 0}, {'id': 229, 'name': '码尚教育87288', 'count': 0}, {'id': 230, 'name': '码尚教育55537', 'count': 0}, {'id': 231, 'name': '码尚教育51487', 'count': 0}, {'id': 232, 'name': '码尚教育89801', 'count': 0}, {'id': 233, 'name': '码尚教育52589', 'count': 0}, {'id': 234, 'name': '码尚教育40643', 'count': 0}, {'id': 235, 'name': '码尚教育71772', 'count': 0}, {'id': 237, 'name': '码尚教育54785', 'count': 0}, {'id': 238, 'name': '码尚教育67689', 'count': 0}, {'id': 243, 'name': '码尚教育59535', 'count': 0}, {'id': 244, 'name': '码尚教育51068', 'count': 0}, {'id': 245, 'name': '码尚教育85866', 'count': 0}]}
[2021-12-19 20:14:35,003] logger_util.py->logs line:73 [INFO] 接口测试成功
[2021-12-19 20:14:35,003] logger_util.py->logs line:73 [INFO] ----------接口测试结束----------

[2021-12-19 20:14:35,009] logger_util.py->logs line:73 [INFO] ----------接口测试开始----------
[2021-12-19 20:14:35,013] logger_util.py->logs line:73 [INFO] 接口名称：文件上传接口
[2021-12-19 20:14:35,014] logger_util.py->logs line:73 [INFO] 请求方式：post
[2021-12-19 20:14:35,014] logger_util.py->logs line:73 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=52_aJyuD9I2_ijEcXrL-scAJsYrVJvtGVxRFsHqDNlzLPJwDFlO_-q49fuy720ZEMRVlfEIQezMtXcbLJh743_pWc7RqHofpWqKX1pg5tlHga_YfS-PcNJ6ULdrIiYTnIX0x_grwsnSdl077xXFLCFbAGAZQT
[2021-12-19 20:14:35,014] logger_util.py->logs line:73 [INFO] 文件上传：{'media': <_io.BufferedReader name='E:\\shu.png'>}
[2021-12-19 20:14:35,783] logger_util.py->logs line:73 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 'url'}]
[2021-12-19 20:14:35,783] logger_util.py->logs line:73 [INFO] 实际结果：{'url': 'http://mmbiz.qpic.cn/mmbiz_png/gwVWn1TZHhWicJ7LUv0wlkVsCzMMG2DRhnAG3HgmBKdMxlGLSlT1NPWPIR43UmEUziaLhLtVQbIAcsBxWibhCydkw/0'}
[2021-12-19 20:14:35,783] logger_util.py->logs line:73 [INFO] 接口测试成功
[2021-12-19 20:14:35,784] logger_util.py->logs line:73 [INFO] ----------接口测试结束----------

[2021-12-19 20:14:35,789] logger_util.py->logs line:73 [INFO] ----------接口测试开始----------
[2021-12-19 20:14:35,791] logger_util.py->logs line:73 [INFO] 接口名称：查询网易新闻
[2021-12-19 20:14:35,791] logger_util.py->logs line:73 [INFO] 请求方式：post
[2021-12-19 20:14:35,792] logger_util.py->logs line:73 [INFO] 请求路径：https://api.apiopen.top/getWangYiNews
[2021-12-19 20:14:35,792] logger_util.py->logs line:73 [INFO] 请求data参数：{'page': 1, 'count': 5}
[2021-12-19 20:14:35,976] logger_util.py->logs line:73 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2021-12-19 20:14:35,978] logger_util.py->logs line:73 [INFO] 实际结果：{'code': 200, 'message': '成功!', 'result': [{'path': 'https://www.163.com/dy/article/G1OBC8LO0514BCL4.html', 'image': 'http://dingyue.ws.126.net/2021/0201/b63f2e50j00qntwfh0020c000hs00npg.jpg?imageView&thumbnail=140y88&quality=85', 'title': '被指偷拿半卷卫生纸 63岁女洗碗工服药自杀 酒店回应', 'passtime': '2021-02-02 10:00:51'}, {'path': 'https://www.163.com/dy/article/G1O1Q9Q2053469M5.html', 'image': 'http://cms-bucket.ws.126.net/2021/0201/9860dbd3p00qntxlo00iqc000s600e3c.png?imageView&thumbnail=140y88&quality=85', 'title': '警方通报＂19岁女大学生学车后失联＂:已遇害 全力侦办', 'passtime': '2021-02-02 10:00:51'}, {'path': 'https://news.163.com/21/0201/10/G1OAFSJR0001899O.html', 'image': 'http://cms-bucket.ws.126.net/2021/0201/9c211c79p00qnu1ff00h8c000s600e3c.png?imageView&thumbnail=140y88&quality=85', 'title': '缅军方接管政权 副总统敏瑞任代总统 白宫紧急回应', 'passtime': '2021-02-02 10:00:51'}, {'path': 'https://www.163.com/dy/article/G1QQ2KIT051482MP.html', 'image': 'http://bjnewsrec-cv.ws.126.net/little61377fe4179p00qnvo3n00ded200u000fwg00it009y.jpg?imageView&thumbnail=140y88&quality=85', 'title': '孙小果母亲讲述经历：＂我老公从没有没办成的事儿＂', 'passtime': '2021-02-02 10:00:50'}, {'path': 'https://www.163.com/dy/article/G1QLGSGT0514BE2Q.html', 'image': 'http://dingyue.ws.126.net/2021/0202/25b0f9dcj00qnvkdk002fc000u000k3m.jpg?imageView&thumbnail=140y88&quality=85', 'title': '安徽名酒产地地下水告急：打井五六百米才出水', 'passtime': '2021-02-02 10:00:50'}]}
[2021-12-19 20:14:35,978] logger_util.py->logs line:73 [INFO] 接口测试成功
[2021-12-19 20:14:35,978] logger_util.py->logs line:73 [INFO] ----------接口测试结束----------

[2021-12-19 20:14:35,984] logger_util.py->logs line:73 [INFO] ----------接口测试开始----------
[2021-12-19 20:14:35,986] logger_util.py->logs line:73 [INFO] 接口名称：测试MD5加密接口
[2021-12-19 20:14:35,986] logger_util.py->logs line:73 [INFO] 请求方式：post
[2021-12-19 20:14:35,986] logger_util.py->logs line:73 [INFO] 请求路径：http://127.0.0.1/md5login
[2021-12-19 20:14:35,986] logger_util.py->logs line:73 [INFO] 请求data参数：{'username': 'admin', 'password': 123}
[2021-12-19 20:14:37,127] logger_util.py->error_log line:68 [ERROR] 发送请求send_request异常：Traceback (most recent call last):
  File "E:\workspace\api_frame\venv\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "E:\workspace\api_frame\venv\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "E:\workspace\api_frame\venv\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\workspace\api_frame\venv\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "E:\workspace\api_frame\venv\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "E:\workspace\api_frame\venv\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\python373\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\python373\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\python373\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\python373\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\python373\lib\http\client.py", line 956, in send
    self.connect()
  File "E:\workspace\api_frame\venv\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "E:\workspace\api_frame\venv\lib\site-packages\urllib3\connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000000049C93C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\workspace\api_frame\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "E:\workspace\api_frame\venv\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "E:\workspace\api_frame\venv\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /md5login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000049C93C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\workspace\api_frame\commons\requests_util.py", line 136, in send_request
    res = RequestsUtil.session.request(method,url,**kwargs)
  File "E:\workspace\api_frame\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\workspace\api_frame\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\workspace\api_frame\venv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /md5login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000049C93C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

[2021-12-19 20:14:37,131] logger_util.py->error_log line:68 [ERROR] 规范YAML测试用例standard_yaml异常：Traceback (most recent call last):
  File "E:\workspace\api_frame\commons\requests_util.py", line 75, in standard_yaml
    return_text = res.text
AttributeError: 'NoneType' object has no attribute 'text'

